/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PC5-RRC-Definitions"
 * 	found in "RRCConnectionRequest.asn1"
 * 	`asn1c -D src -pdu=auto -fcompound-names -no-gen-OER -no-gen-example -fno-include-deps`
 */

#ifndef	_SBCCH_SL_BCH_MessageType_V2X_r14_H_
#define	_SBCCH_SL_BCH_MessageType_V2X_r14_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MasterInformationBlock-SL-V2X-r14.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SBCCH-SL-BCH-MessageType-V2X-r14 */
typedef MasterInformationBlock_SL_V2X_r14_t	 SBCCH_SL_BCH_MessageType_V2X_r14_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SBCCH_SL_BCH_MessageType_V2X_r14;
asn_struct_free_f SBCCH_SL_BCH_MessageType_V2X_r14_free;
asn_struct_print_f SBCCH_SL_BCH_MessageType_V2X_r14_print;
asn_constr_check_f SBCCH_SL_BCH_MessageType_V2X_r14_constraint;
ber_type_decoder_f SBCCH_SL_BCH_MessageType_V2X_r14_decode_ber;
der_type_encoder_f SBCCH_SL_BCH_MessageType_V2X_r14_encode_der;
xer_type_decoder_f SBCCH_SL_BCH_MessageType_V2X_r14_decode_xer;
xer_type_encoder_f SBCCH_SL_BCH_MessageType_V2X_r14_encode_xer;
jer_type_encoder_f SBCCH_SL_BCH_MessageType_V2X_r14_encode_jer;
per_type_decoder_f SBCCH_SL_BCH_MessageType_V2X_r14_decode_uper;
per_type_encoder_f SBCCH_SL_BCH_MessageType_V2X_r14_encode_uper;
per_type_decoder_f SBCCH_SL_BCH_MessageType_V2X_r14_decode_aper;
per_type_encoder_f SBCCH_SL_BCH_MessageType_V2X_r14_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SBCCH_SL_BCH_MessageType_V2X_r14_H_ */
#include <asn_internal.h>
